### ISSUE TITLE
Importing the URL

### ISSUE THREAD

**Issue by judin** [designbyfront/Import-Data-into-ExpressionEngine#3]
Hello,

Although it pains me to suggest this, would it be possible to have the option to import a url, rather than it being generated from the title?

Thanks,
Justin

**Comment by designbyfront** [comment]
Hi Justin,

It is possible to load a remote file as an input. In this case I have created a "_remote CSV file_" input type - [Remote_csv_file.class.php](http://github.com/designbyfront/Import-Data-into-ExpressionEngine/blob/master/EE1/system/modules/import_data/files/input_types/Remote_csv_file.class.php)
[I'm not quite sure what you meant by "_generated from the title_"]

To use this input type, choose it from the drop down type menu and provide a text file containing just the URL of the remote CSV file.

**Note:** This class has not been built for efficiency (eg. large remote files) or elegant degradation when encountering errors (eg. inaccessible remote file).

I hope this can be of use.

Regards,
Alistair

**Comment by judin** [comment]
Hi Alistair,

Sorry for not making this thought clear. I was wondering if it would be possible for another option for URL Titles.
i) Create the URL Title using the text in the Page Title (as is now)
ii) Import the URL Title (as named on the Publish page) from the CSV

I can see other people finding this useful too, having review Solspace's plugin, CSVGrab, DataGrab, amongst others.

However, the information posted above is very useful and I will be taking a look at this today.

Justin

**Comment by designbyfront** [comment]
Hi Justin,

Apologies, I had completely misunderstood. Reading back now that I know what it's about, you make complete sense! It finally clicked when I read your other issue.

I have added in the "_url_title_" field so that it can be imported to :)

Regards,
Alistair

**Comment by judin** [comment]
Fantastic - thank you!
