### ISSUE TITLE
Related entries question or suggested request

### ISSUE THREAD

**Issue by judin** [designbyfront/Import-Data-into-ExpressionEngine#4]
Hey Alistair,

Forgive me for creating seperate topics, but that's how I would usually choose to work.

Something I've been looking into and saw others looking for a similar thing is the possibility to relate an entry based on a unique identifier within an entry, that is NOT the Title.

I'm currently working on two projects where I hadn't even thought about using a data import product, until I saw how easily this one would work! Therefore my example below is from a live project.

Each individual item in a shop has its own barcode/Product Code/SKU which they use to unique identify a line item, and they might want to relate an entry based on the SKU. For example, a t-shirt may come in red, green and blue, and they all need to be related. Yes, they could be related by title, but it would be neat to be able to import the relationship by the SKU.

The alternative to this would be to set the SKU in the entry Title. Not quite as neat, but also not difficult. However, this is where setting the URL Title for a page from the Title field wouldn't be any good (see my other reply this morning).

Anyway, I'm taking up enough of your time, but I thought these suggestions may help you and/or others in the future, too.

Justin

**Comment by designbyfront** [comment]
Hi Justin,

No worries on creating a new issue - makes it easier to manage :)

"_relate an entry_" - are you referring to the ExpressionEngine relationship field?
If so, then yes, you can import a relationship for any field in the weblog.

So in your example, you have a "_Products_" weblog with a "_Title_", "_SKU_" and "_Related Product_" fields.
Your input file has the columns "_title_", "_sku_" and "_related_".

When you import, make sure that you tick that relationships exist (in stage 1).
In stage 2, you can then define the relationship; in this case the "_related_" column of the input file will contain a "_SKU_" of the "_Products_" weblog.
In stage 3, you match the "_related_" column of the input file to the "_Related Product_" field.

A good way to think about it is that you have a unique identifier as input. But you don't want it to be used as the value, you want an entry to be used instead. So you are telling the module (in stage 2) that the unique input should actually be swapped for an entry which has that unique value in it.

I hope that makes sense. Let me know if you need more clarification or if I've misunderstood.
Suggestions are always welcome; I'm always looking to make this module easier and better to use :)

Regards,
Alistair

**Comment by judin** [comment]
It works!! Third time lucky. I still have to say I find it difficult to get my head round this (is it because I'm blonde?)!

Thank you very much.

**Comment by designbyfront** [comment]
Hi Justin,

Good to know :)
I must say it is a little tricky to get your head around the concept. Perhaps there's a better way to articulate creating a relationship, but this way made sense when I was designing it.

Glad you got it working!

Regards,
Alistair
