### ISSUE TITLE
Importing blank fields as 0

### ISSUE THREAD

**Issue by judin** [designbyfront/Import-Data-into-ExpressionEngine#5]
Hello,

Was just importing some content where there are some blank fields. I noticed that, rather than importing nothing, it imports as a 0 (zero).

Is there any way to fix this up?

Have a good weekend,
Justin

**Comment by designbyfront** [comment]
Hi Justin,

Thanks for letting me know about this. I haven't come across this issue - I've tried importing blank data into numerous field types none of which have achieved this.
Can you tell me more about the weblog you were importing into, namely what was the field type?
Were you inputting nothing (in a csv ,,) or blank string (in a csv ,'', or ,"",)?

Any more information you can give will help me to track down this issue.

Regards,
Alistair

**Comment by judin** [comment]
Oh, who knows! I can't replicate it either now. The fields were definitely csv ,, but I don't know why it buggered up!
