### ISSUE TITLE
Import now overwriting categories

### ISSUE THREAD

**Issue by judin** [designbyfront/Import-Data-into-ExpressionEngine#8]
Hi Alistair,

Well, I updated to the most recent version of IDiEE (nice acronym) and now for me it's overwriting categories, whether -Default- is selected or choosing a data column with only a single category and selecting Disable Overwrite.

Is it my installation being funny do you think?

J

**Comment by designbyfront** [comment]
Hi Justin,

Did you get this issue sorted?

Regards,
Alistair

**Comment by judin** [comment]
No, unfortunately not :-(

Dunno what's happening really.

**Comment by judin** [comment]
So back to this thread for the Category issue, importing seems to be bringing across the correct details BUT is most definitely overwriting categories whether I like it or not.

For now, I'm exporting the category_field_data table, importing everything else, then putting that particular data back. I realise it must be something on the site, either configuration or plugin that's causing the issue, but I'm flummoxed :-) Need to learn me more PHP-foo.

**Comment by judin** [comment]
Well, it WAS overwriting categories in a previous version, but now it's not...

My imports were NOT showing... then I thought, what might I have changed. Daylight Savings Time. Oh I'm such a fool. I changed this about 2 weeks ago, not thinking it would cause implications now!!!

So, consider this 'non-issue' closed... for now!!
