### ISSUE TITLE
Latest version not loading stage 2

### ISSUE THREAD

**Issue by judin** [designbyfront/Import-Data-into-ExpressionEngine#9]
Hi Alistair,

Hope you're well? I've been trying to install the latest version today but can't get past Stage 1. It just doesn't like Stage 2.

**Comment by judin** [comment]
Just been playing around again. The version 2 (5th March) build gives me a 500 Server Error when moving from Stg. 1 to Stg. 2 - although the file is successfully uploaded.

J

**Comment by designbyfront** [comment]
Hi Justin,

That's very strange.
I just installed a fresh EE1.6.9 and downloaded the IDiEE 2.0 (I like the acronym!) - no problems getting from stage 1 to 2.

Previously I had been running my builds on local linux servers, but I decided to install this on my local windows machine; the paths generated needed tweaking to get it to upload files. What operating system are you running?
Perhaps another add-on is causing issues - is there anything new you have installed lately which might be clashing?
In _mcp.import_data.php_ there are some debug lines which can be uncommented - the two lines below "// Uncomment for debugging". Perhaps this can shed some light on where the issue is occurring.

Regards,
Alistair

**Comment by judin** [comment]
I'll have a look now at the uncomment for debug bits. The only thing I
installed was SuperSearch by Solspace, and I've tried it disabled. I'm going
to try uninstalling this before trying anything else.

I'm now not able to successfully import anything, as everytime I import it
overwrites the categories, whether the 'Disable overwrite' option is ticked
or not.

**Comment by judin** [comment]
Having uncommented, the errors are:

Warning: require_once(/var/www/sitename.co.uk/html/system/modules/import_data/files/input_types/input_type.interface.php): failed to open stream: No such file or directory in /var/www/sitename.co.uk/html/system/modules/import_data/files/classes/supporting/stage_library.class.php on line 62 Fatal error: require_once(): Failed opening required '/var/www/sitename.co.uk/html/system/modules/import_data/files/input_types/input_type.interface.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/sitename.co.uk/html/system/modules/import_data/files/classes/supporting/stage_library.class.php on line 62 

This did lead me to the question of whether I needed PEAR installed? I've done so using the default locations etc. I'm running Ubuntu 10.10 32 bit with latest LAMP.

**Comment by designbyfront** [comment]
Hi Justin,

The problem appears to be that the file:
**/var/www/sitename.co.uk/html/system/modules/import_data/files/input_types/input_type.interface.php**
does not seem to be valid.
PHP throws a warning when it cannot be found and then bombs out with a fatal error when the missing code is needed.
As far as I know, the pear reference is in relation to where PHP will look when a file is "required". It's not needed to run the module.

I think It might be a character case issue - 
in _/var/www/sitename.co.uk/html/system/modules/import_data/files/classes/supporting/stage_library.class.php_ on line 62 change "__i__nput_type.interface.php" to "__I__nput_type.interface.php" (capitalise the first letter).

If this does not work, can you make sure that the path above is valid (it appears to me) and that the file permissions are set so it can be accessed.
Let me know how you get on.

Regards,
Alistair

**Comment by judin** [comment]
Thanks Alistair - it now loads!

Unfortunately, when I try and import CSV data (the same as previously), it
overwrites categories (even with Disable overwrite behaviour checked).

I'm going to try and get TSV files working to see if this resolves the
issue. After that, I'll remove XHTML data from within the database as I'm
wondering if there's some nasty MS Word style XML or HTML tags that have
gotten imported from our old system.

Will keep you posted,
J
